version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - media_files:/app/media
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - app_network

  celery_worker:
    build: .
    command: celery -A asset_tracker worker -l INFO
    depends_on:
      - redis
      - web
    env_file: .env
    networks:
      - app_network

  celery_beat:
    build: .
    command: celery -A asset_tracker beat -l INFO
    depends_on:
      - redis
      - web
    env_file: .env
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/static
      - media_files:/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app_network

volumes:
  postgres_data:
  static_files:
  media_files:

networks:
  app_network:
    driver: bridge