# Generated by Django 5.0.6 on 2025-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0003_fuelrecord_tirerecord_alter_car_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="body",
            field=models.CharField(
                choices=[
                    ("Sedan", "Sedan"),
                    ("Hatchback", "Hatchback"),
                    ("SUV", "SUV"),
                    ("Ute", "Ute"),
                    ("Van", "Van"),
                    ("Truck", "Truck"),
                    ("EWP", "EWP"),
                    ("Trailer", "Trailer"),
                    ("Other", "Other"),
                ],
                default="Sedan",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="state",
            field=models.CharField(
                choices=[
                    ("NSW", "New South Wales"),
                    ("VIC", "Victoria"),
                    ("QLD", "Queensland"),
                    ("WA", "Western Australia"),
                    ("SA", "South Australia"),
                    ("TAS", "Tasmania"),
                    ("NT", "Northern Territory"),
                    ("ACT", "Australian Capital Territory"),
                ],
                db_index=True,
                default="R1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NSW", "New South Wales"),
                    ("VIC", "Victoria"),
                    ("QLD", "Queensland"),
                    ("WA", "Western Australia"),
                    ("SA", "South Australia"),
                    ("TAS", "Tasmania"),
                    ("NT", "Northern Territory"),
                    ("ACT", "Australian Capital Territory"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="state",
            field=models.CharField(
                choices=[
                    ("NSW", "New South Wales"),
                    ("VIC", "Victoria"),
                    ("QLD", "Queensland"),
                    ("WA", "Western Australia"),
                    ("SA", "South Australia"),
                    ("TAS", "Tasmania"),
                    ("NT", "Northern Territory"),
                    ("ACT", "Australian Capital Territory"),
                ],
                default="NSW",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="store",
            field=models.CharField(
                choices=[
                    ("authorized_dealer", "Authorized Dealer"),
                    ("retail_store", "Retail Store"),
                    ("online_store", "Online Store"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="tool_name",
            field=models.CharField(
                choices=[
                    ("safety_harness", "Safety Harness"),
                    ("safety_helmet", "Safety Helmet"),
                    ("safety_glasses", "Safety Glasses"),
                    ("safety_gloves", "Safety Gloves"),
                    ("first_aid_kit", "First Aid Kit"),
                    ("fire_extinguisher", "Fire Extinguisher"),
                    ("rescue_kit", "Rescue Kit"),
                    ("spill_kit", "Spill Kit"),
                    ("screwdriver_set", "Screwdriver Set"),
                    ("wrench_set", "Wrench Set"),
                    ("plier_set", "Plier Set"),
                    ("hammer", "Hammer"),
                    ("measuring_tape", "Measuring Tape"),
                    ("drill_cordless", "Cordless Drill"),
                    ("impact_driver", "Impact Driver"),
                    ("angle_grinder", "Angle Grinder"),
                    ("heat_gun", "Heat Gun"),
                    ("multimeter", "Multimeter"),
                    ("cable_tester", "Cable Tester"),
                    ("crimping_tool", "Crimping Tool"),
                    ("laser_level", "Laser Level"),
                    ("laptop", "Laptop"),
                    ("printer", "Printer"),
                    ("label_maker", "Label Maker"),
                    ("barcode_scanner", "Barcode Scanner"),
                    ("tool_box", "Tool Box"),
                    ("tool_bag", "Tool Bag"),
                    ("ladder", "Ladder"),
                    ("trolley", "Trolley"),
                    ("generator", "Generator"),
                    ("lighting_equipment", "Lighting Equipment"),
                    ("traffic_cone", "Traffic Cone"),
                    ("warning_sign", "Warning Sign"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
