# Generated by Django 5.0.6 on 2025-04-26 12:33

from django.db import migrations


def convert_states_forward(apps, schema_editor):
    # Get the models
    Profile = apps.get_model('tracking', 'Profile')
    Tool = apps.get_model('tracking', 'Tool')
    Car = apps.get_model('tracking', 'Car')

    # Mapping of old values to new values
    state_mapping = {
        'R1': 'NSW',  # Assuming Region 1 maps to NSW
        'R2': 'VIC',  # Assuming Region 2 maps to VIC
        'R3': 'QLD',  # Assuming Region 3 maps to QLD
        'R4': 'WA',   # Assuming Region 4 maps to WA
        'R5': 'SA',   # Assuming Region 5 maps to SA
        'OTHER': 'NSW'  # Default to NSW for OTHER
    }

    # Update Profile states
    for profile in Profile.objects.all():
        if profile.state in state_mapping:
            profile.state = state_mapping[profile.state]
            profile.save()

    # Update Tool states
    for tool in Tool.objects.all():
        if tool.state in state_mapping:
            tool.state = state_mapping[tool.state]
            tool.save()

    # Update Car states
    for car in Car.objects.all():
        if car.state in state_mapping:
            car.state = state_mapping[car.state]
            car.save()


def convert_states_backward(apps, schema_editor):
    # Get the models
    Profile = apps.get_model('tracking', 'Profile')
    Tool = apps.get_model('tracking', 'Tool')
    Car = apps.get_model('tracking', 'Car')

    # Reverse mapping of new values to old values
    reverse_mapping = {
        'NSW': 'R1',
        'VIC': 'R2',
        'QLD': 'R3',
        'WA': 'R4',
        'SA': 'R5',
        'TAS': 'OTHER',
        'NT': 'OTHER',
        'ACT': 'OTHER'
    }

    # Update Profile states
    for profile in Profile.objects.all():
        if profile.state in reverse_mapping:
            profile.state = reverse_mapping[profile.state]
            profile.save()

    # Update Tool states
    for tool in Tool.objects.all():
        if tool.state in reverse_mapping:
            tool.state = reverse_mapping[tool.state]
            tool.save()

    # Update Car states
    for car in Car.objects.all():
        if car.state in reverse_mapping:
            car.state = reverse_mapping[car.state]
            car.save()


class Migration(migrations.Migration):
    dependencies = [
        ('tracking', '0004_update_state_choices'),
    ]

    operations = [
        migrations.RunPython(convert_states_forward, convert_states_backward),
    ]
